version: '3.7'

services:
  db:
    image: postgres:11
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: ./web-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./web-app:/usr/src/app/
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
