version: '3.7'

services:
  db:
    image: postgres:11
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - net

  web:
    build:
      context: ./web-app
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    command: gunicorn qfieldcloud.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - ./user_projects_files:/home/app/web/user_projects_files
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - net

  caddy:
    image: caddy/caddy:alpine
    restart: unless-stopped
    depends_on:
      - web
    environment:
      ACME_AGREE: "true"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    networks:
      - net
    ports:
      - 80:80
      - 443:443

volumes:
  static_volume:
  media_volume:

networks:
  net:
