version: '3.7'

services:
  db:
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  web:
    build:
      context: ./web-app
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    command: gunicorn qfieldcloud.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - ./web-app/user_projects_files:/home/app/web/user_projects_files
      - ./web-app/db.sqlite3:/home/app/web/db.sqlite3
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  nginx:
    build: ./docker-nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
