version: '3.7'

services:
  db:
    image: postgres:11
    restart: unless-stopped
    environment:
      - POSTGRES_USER=qfieldcloud_dev_db_admin
      - POSTGRES_PASSWORD=zc3muugx
      - POSTGRES_DB=qfieldcloud_dev_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - net

  web:
    build: ./web-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./web-app:/usr/src/app/
      - ./user_projects_files:/usr/src/app/user_projects_files
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
    networks:
      - net

  qgis:
    build:
      context: .
      dockerfile: ./docker-qgis/Dockerfile
      args:
        QGIS_VERSION: final-3_10_3
    tty: true
    command: bash -c "echo QGIS builded"

  docker-host:
    image: qoomon/docker-host:2.4.2
    restart: unless-stopped
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    networks:
      - net

  # Useful to test if the docker-host can actually communicate with the host
  # listen on the host with nc -p 2323 -lk
  #
  # tcp_message_emitter:
  #   depends_on: [ docker-host ]
  #   image: alpine
  #   command: [ "sh", "-c", "while :; do date; sleep 1; done | nc 'docker-host' 2323 -v"]
  #   networks:
  #     - net

volumes:
  postgres_data:

networks:
  net:
    # driver: bridge
