version: '3.7'

services:
  db:
    image: postgres:11
    restart: unless-stopped
    environment:
      - POSTGRES_USER=qfieldcloud_dev_db_admin
      - POSTGRES_PASSWORD=zc3muugx
      - POSTGRES_DB=qfieldcloud_dev_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: ./web-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./web-app:/usr/src/app/
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev

  qgis:
    build:
      context: .
      dockerfile: ./docker-qgis/Dockerfile
      args:
        QGIS_VERSION: final-3_10_3
    tty: true
    command: bash -c "echo QGIS builded"

volumes:
  postgres_data:
