name: Test
on: push
jobs:
  test:
    name: Code check and tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install flake8
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            flake8
            nose
      - name: Run Flake8
        run: python -m flake8 --ignore=E501,F401 web-app
      - name: Install docker and docker compose
        run: |
          sudo apt update
          sudo apt install docker
          sudo apt install docker-compose
      - name: Build and run docker containers
        run: docker-compose up -d --build
      - name: Run Django unit and functional tests
        run: docker-compose run web python manage.py test -v2
      - name: Run QGIS caller unit tests
        run: nosetests -v docker-qgis/tests
