name: Test
on: push
jobs:
  test:
    name: Code check and tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.5
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install pipenv dependencies
        run: |
          cd orchestrator
          pipenv install
      - name: Check code with Flake8
        run: |
          cd orchestrator
          pipenv run python -m flake8 --ignore=E501,F401,W503 ../django-app
      - name: Build and run docker containers
        run: |
          cp .github/workflows/.env.app.test conf/.env.app
          cp .github/workflows/.env.db.test conf/.env.db
          docker-compose up -d --build
      - name: run RQ workers
        run: |
          cd orchestrator
          pipenv run rq worker export delta &
      - name: Run unit and integration tests
        run: |
          pwd
          docker-compose run app python manage.py test -v2

