name: Test
on: push
jobs:
  test:
    name: Code check and tests
    runs-on: ubuntu-18.04
    env:
      STORAGE_ACCESS_KEY_ID: ${{ secrets.STORAGE_ACCESS_KEY_ID }}
      STORAGE_SECRET_ACCESS_KEY: ${{ secrets.STORAGE_SECRET_ACCESS_KEY }}
      STORAGE_BUCKET_NAME: qfieldcloud-test
      STORAGE_REGION_NAME: ${{ secrets.STORAGE_REGION_NAME }}
      STORAGE_ENDPOINT_URL: ${{ secrets.STORAGE_ENDPOINT_URL }}
      MINIO_PORT: 8007
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pipenv
        run: pip install pipenv
      - name: Prepare docker-compose override file
        run: |
          ln -s docker-compose.override.local.yml docker-compose.override.yml
      - name: Check code formatting
        run: |
          pipenv install pre_commit
          pipenv run python -m pre_commit run --all-files
      - name: Export the env variables file
        run: |
          cp .env.example .env
          export $(egrep -v '^#' .env | xargs)
      - name: Pull docker containers
        run: docker-compose pull
      - name: Build and run docker containers
        run: |
          docker-compose up -d --build
      - name: Run unit and integration tests
        run: |
          docker-compose run app python manage.py test -v2 qfieldcloud

      - name: "failure logs"
        if: failure()
        run: |
          docker-compose logs
