name: Test
on: push
jobs:
  test:
    name: Code check and tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pypi requirements
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            flake8
            nose
            flask
            gunicorn
            docker
      - name: Run Flake8
        run: python -m flake8 --ignore=E501,F401,W503 web-app
      - name: Run containers
        run: |
          docker-compose up -d --build
      - name: Run orchestrator and tests
        run: |
          gunicorn -b 0.0.0.0:5000 "orchestrator.orchestrator:app" &
          docker-compose run web python manage.py test -v2
      - name: Run QGIS caller unit tests
        run: nosetests -v docker-qgis/tests
